test: add testcases for Button Component
rubemfsv/clean-react-app pull request #58
Opened 2023-10-07 07:17 UTC by coldrohak

Wrote the unit tests for button component inside a new file index.spec.tsx
Closes #9

2023-10-08 06:24 UTC, coldrohak commented
Hey @rubemfsv, please review it once

2023-10-08 13:33 UTC, rubemfsv requested changes

2023-10-08 13:33 UTC, rubemfsv commented on src/presentation/components/Button/index.spec.tsx
> +      title: 'Test Button'
use faker here

2023-10-08 13:33 UTC, rubemfsv commented on src/presentation/components/Button/index.spec.tsx
> +      title: 'Test Button',
use faker here

2023-10-08 13:33 UTC, rubemfsv commented on src/presentation/components/Button/index.spec.tsx
> +      title: 'Test Button',
use faker here and below

2023-10-08 13:33 UTC, rubemfsv commented on src/presentation/components/Button/index.spec.tsx
> +    const props: IButtonProps = {
use faker here and below

2023-10-08 13:33 UTC, rubemfsv commented on src/presentation/components/Button/index.spec.tsx
> +      title: 'Test Button',
use faker to handle these data

2023-10-08 13:33 UTC, rubemfsv commented on src/presentation/components/Button/index.tsx
> +export {IButtonProps}
export in line 5, like export interface...

2023-10-09 16:36 UTC, rubemfsv approved these changes, later dismissed

2023-10-09 17:41 UTC, coldrohak commented
Hey @rubemfsv , sry i didnt knew about dismiss review actually the tests after your approval were failing here so i pushed a new commit, Can you please guide me if something needs to be corrected?

2023-10-09 17:44 UTC, rubemfsv approved these changes

2023-10-09 17:53 UTC, coldrohak commented
@rubemfsv , all of tests are passing on my device but why are they failing on github, please help I am not able to figure out...

2023-10-09 18:23 UTC, merged