SignUp page test
rubemfsv/clean-react-app pull request #59
Opened 2023-10-07 07:52 UTC by Vidip-Ghosh

Wrote the test case for SignUp Page. 
Closes #11

2023-10-08 13:41 UTC, rubemfsv requested changes

2023-10-08 13:41 UTC, rubemfsv commented on src/presentation/pages/SignUp/index.spec.tsx
> +    authenticationSpy: AuthenticationSpy
please, run `npm run format:fix` before to run prettier in this file

2023-10-08 13:41 UTC, rubemfsv commented on src/presentation/pages/SignUp/index.spec.tsx
> +import { type } from "os";
I think its not necessary, verity all imports to check if all is necessary

2023-10-08 13:41 UTC, rubemfsv commented on src/presentation/pages/SignUp/index.spec.tsx
> +    await simulateValidSubmit(email,password,name,confirm_password)
put in order, due to the order of the simulateValidSubmit. And password and confirmPassword should be the same to be a valid submit

2023-10-08 13:41 UTC, rubemfsv commented on src/presentation/pages/SignUp/index.spec.tsx
> +    const validationError = faker.random.words()
you declared here and not used... I think it is to be injected in the sut

2023-10-09 17:24 UTC, Vidip-Ghosh commented
<img width="1332" alt="Screenshot 2023-10-09 at 22 52 10" src="https://github.com/rubemfsv/clean-react-app/assets/91741581/ec77a0c5-3f3c-4e1c-b62d-f3978911f222">
Got this error while pushing

2023-10-09 19:55 UTC, rubemfsv commented
@Vidip-Ghosh solve this test error... This error is because the test is broken

2023-10-10 17:45 UTC, Vidip-Ghosh commented
<img width="867" alt="Screenshot 2023-10-10 at 23 15 02" src="https://github.com/rubemfsv/clean-react-app/assets/91741581/1f271bbc-1548-497f-bb15-efdab8baeb70">
Getting error in this line. Please tell what to do as 1 test case is failing due to this location one.

2023-10-12 12:21 UTC, rubemfsv commented
@Vidip-Ghosh run npm install again... This error shouldn't happen because you check location in one test before. However, is also missing some fixes pointed in the review

2023-10-17 03:54 UTC, Vidip-Ghosh commented
@rubemfsv still some tests are getting failed.

2024-02-24 03:31 UTC, closed without merging