Header Template for clean react app
rubemfsv/clean-react-app pull request #61
Opened 2023-10-08 18:52 UTC by Ashok-Kumar-dharanikota

- [x] Commit messages are ready to go in the changelog (see below for details)
- [x] PR template filled in (see below for details)

### PR Template

_Please describe what this PR is for, or link the issue that this PR fixes_

issue #17 

The purpose of this issue is to add common sections as a template to this project. So user can use the template directly instead of re-creating common stuff again.

In this PR,

I added two components and wrapped the navigation component inside the Header component and the Header component inside the Template. Users can also access the Header and Navigation components individually. If he wants to create a custom Header and navigation.

folder structure 
```
  presentation/
    components/
      Template/
        Header/
              index.tsx // contains header
              styles.scss
        Navigation/
              index.tsx // contains navigation
              styles.scss
        index.tsx // mount header and navigation and provides a template
        styles.scss
    pages/
      Dashboard/
```

_Thanks again!_

2023-10-11 12:01 UTC, rubemfsv requested changes
Could you provide some print screens?

2023-10-11 12:01 UTC, rubemfsv commented on src/presentation/pages/Dashboard/index.tsx
> +      <div className={Styles.App}>
use the app in lowercase

2023-10-11 12:01 UTC, rubemfsv commented on src/presentation/pages/Dashboard/styles.scss
> +.App {
use the app in lowercase

2023-10-11 12:01 UTC, rubemfsv commented on src/presentation/components/Template/Header/styles.scss
> +.Container {
use the container in lowercase

2023-10-11 12:01 UTC, rubemfsv commented on src/presentation/components/Template/Header/index.tsx
> +    <div className={Styles.Container}>
use the container in lowercase

2023-10-11 12:01 UTC, rubemfsv commented on src/presentation/components/Template/Header/index.tsx
> +        src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg"
I suggest you to put something written like "My App", as I did here https://main--cheery-shortbread-5efb5b.netlify.app/

it's easier to change

2023-10-11 15:16 UTC, Ashok-Kumar-dharanikota commented
Hi @rubemfsv ,

I fixed the changes and this is the result

![image](https://github.com/rubemfsv/clean-react-app/assets/103619560/bebd4396-e80d-4ddf-98a8-4a635d78e6bc)

2023-10-17 12:23 UTC, rubemfsv commented
@Ashok-Kumar-dharanikota could you take a look at the failing tests?

2023-10-17 18:36 UTC, Ashok-Kumar-dharanikota commented
Hi @rubemfsv ,

I found the reason why it's failing. Due to a naming issue, It is unable to find the file. So I renamed the file name to styles.scss before that I synced the project.

2023-10-26 14:20 UTC, rubemfsv approved these changes

2023-10-26 14:20 UTC, merged